### ISSUE TITLE
Error since 2.8.d

### ISSUE THREAD

**Issue by buchanan-fh** [xbgmsharp/piwigo-openstreetmap#126]
Hello,

I just upgraded to v2.8.d, and get the following error when trying to access the config page :

_Parse error: syntax error, unexpected ',' in /home/carte-fh/www/galerie_photo/plugins/piwigo-openstreetmap/admin/admin_config.php on line 202_

**Comment by xbgmsharp** [comment]
I updated the branch, please re-download the archive, the fix should be included.

**Comment by buchanan-fh** [comment]
I downloaded this archive : https://github.com/xbgmsharp/piwigo-openstreetmap/archive/v2.8.d.zip  but the problem is still there

**Comment by xbgmsharp** [comment]
Good point, I was referring to the PWG plugin manager. I updated branch 2.8.c and 2.8.d as they both have the same issue.
Anyway for github, i created a new release https://github.com/xbgmsharp/piwigo-openstreetmap/archive/2.8.d.zip

**Comment by buchanan-fh** [comment]
Thank's, it worked

**Comment by ChrisBrunnen** [comment]
I am also getting this error-  Parse error: syntax error, unexpected ',' in D:\Sites\cjbphotography.co.uk\public_html\photo_new\plugins\piwigo-openstreetmap\admin\admin_config.php on line 202

I've deleted it from Plugin Manager and re-downloaded and installed it with no luck. What am I doing wrong please?

**Comment by xbgmsharp** [comment]
I re-create the archive on PEM. Sorry.

**Comment by ChrisBrunnen** [comment]
That's done the trick, thank you
