### ISSUE TITLE
break with https and no-mixed-content

### ISSUE THREAD

**Issue by Sebas-St** [xbgmsharp/piwigo-openstreetmap#58]
When viewing the album over HTTPS the map doesn't show if you don't allow mixed-content even if you choose mapnik which seems to (partially?) use https. Some of the links to the server with piwigo also try to connect over HTTP.

Can it either always use HTTPS where possible, or atleast when piwigo is configures to use HTTPS respect that?

Thanks for making this great module though!

**Comment by xbgmsharp** [comment]
This has been fixed via #56 and #21.
Update the plugin using the git version and report if it work for you.

**Comment by xbgmsharp** [comment]
Could you confirm the issue is solve after updating to the latest version from Git?
https://github.com/xbgmsharp/piwigo-openstreetmap#installation

**Comment by lewie** [comment]
@xbgmsharp,
this great Module piwigo-openstreetmap (current master) still does not respect Https.

````
...
Gemischte (unsichere) Anzeige-Inhalte von "http://c.tile.openstreetmap.de/tiles/osmde/2/1/1.png" werden auf einer sicheren Seite geladen[Weitere Informationen] leaflet.js:7:0
Gemischte (unsichere) Anzeige-Inhalte von "http://a.tile.openstreetmap.de/tiles/osmde/2/2/1.png" werden auf einer sicheren Seite geladen[Weitere Informationen] leaflet.js:7:0
Gemischte (unsichere) Anzeige-Inhalte von "http://a.tile.openstreetmap.de/tiles/osmde/2/1/2.png" werden auf einer sicheren Seite geladen[Weitere Informationen] leaflet.js:7:0
Gemischte (unsichere) Anzeige-Inhalte von "http://b.tile.openstreetmap.de/tiles/osmde/2/2/2.png" werden auf einer sicheren Seite geladen[Weitere Informationen] leaflet.js:7:0
Gemischte (unsichere) Anzeige-Inhalte von "http://b.tile.openstreetmap.de/tiles/osmde/2/0/1.png" werden auf einer sicheren Seite geladen[Weitere Informationen] leaflet.js:7:0
Gemischte (unsichere) Anzeige-Inhalte von "http://b.tile.openstreetmap.de/tiles/osmde/2/3/1.png" werden auf einer sicheren Seite geladen[Weitere Informationen] leaflet.js:7:0
Gemischte (unsichere) Anzeige-Inhalte von "http://c.tile.openstreetmap.de/tiles/osmde/2/0/2.png" werden auf einer sicheren Seite geladen[Weitere Informationen] leaflet.js:7:0
Gemischte (unsichere) Anzeige-Inhalte von "http://c.tile.openstreetmap.de/tiles/osmde/2/3/2.png" werden auf einer sicheren Seite geladen[Weitere Informationen]
...
````

**Comment by xbgmsharp** [comment]
Not related to the plugin the website `openstreetmap.de` does not provide HTTPS service.

**Comment by lewie** [comment]
Ah, ok if they do not provide https, then there is no way to get it... ;-)

Thanks xbgmsharp

**Comment by xbgmsharp** [comment]
Closing, there is no solution for provide that don't support HTTPS. As of today openstreetmap.de still don't offer HTTPS access.
```
curl https://c.tile.openstreetmap.de/tiles/osmde/2/3/2.png
*   Trying 139.17.3.229...
* connect to 139.17.3.229 port 443 failed: Connection refused
* Failed to connect to c.tile.openstreetmap.de port 443: Connection refused
* Closing connection 0
```
